### ISSUE TITLE
Wanting to add GradientStop.Offset

### ISSUE THREAD

**Issue by JerryNixon** [mrlacey/UwpDesignTimeData#3]
Okay, so, I like this. I tried adding a GradientStop.Offset property of type double. Like:

````csharp
public static readonly DependencyProperty OffsetProperty =
            DependencyProperty.Register("Offset", typeof(double), typeof(DesignTime), new PropertyMetadata(null));
public static void SetOffset(GradientStop element, double value)
{
    element.SetValue(DesignTime.OffsetProperty, value);
    if (Windows.ApplicationModel.DesignMode.DesignModeEnabled)
    {
        element.Offset = value;
    }
}
public static double GetOffset(GradientStop element)
    => (double)element.GetValue(DesignTime.OffsetProperty);
````

My plan was to use it. Like this:

````xml
<TextBlock Text="{x:Bind Header}"
            dt:DesignTime.Text="Designtime Header Text Jerry Nixon"
            Style="{StaticResource HeaderTextBlockStyle}">
    <TextBlock.Foreground>
        <LinearGradientBrush EndPoint="0.5,1" StartPoint="0.5,0">
            <GradientStop Color="#FFFF008B" Offset="0" />
            <GradientStop Color="#FFE8FF00" Offset="1"/>
        </LinearGradientBrush>
    </TextBlock.Foreground>
</TextBlock>
````
But I only seemed to get this.

![image](https://user-images.githubusercontent.com/1749983/63070138-36e90e00-bed7-11e9-906e-4a5b6e2d8215.png)

Attaching to `UwpSurface.exe` didn't seem to help me debug either.

Anyway, what are your thoughts? Possible?

**Comment by mrlacey** [comment]
Hi @JerryNixon Sorry, I only saw this today.

![image](https://user-images.githubusercontent.com/189547/64349477-f456b500-cfee-11e9-89a0-26d43689a6ee.png)

The code you've written works for me.

I think the blue squiggly underline is an error caching issue. I found that closing and reopening the XAML file caused it to go away.

I'll release an updated version of the library that has the `Offset` property included by default and so this shouldn't be an issue going forward.

**Comment by mrlacey** [comment]
V1.2 has the `Offset` property included.

I think the invalid error message is due to an issue with the XAML validation engine. Unfortunately, there's no extensibility in the way XAML is validated by VS and so there isn't a workaround beyond compiling the project and reopening the file. :(

**Comment by mrlacey** [comment]
I think the need to recompile (and remove the blue squiggles) is because the compilation that's done to validate the XAML (and produce tags, error-list entries, etc.) is happening separately to the compilation that's done to create the contents of the designer. I don't see any way to change this externally and so this is something that we'll have to live with for now. 
There are much higher priority items I'd like to see the XAML designer team working on and so don't see any value in escalating this to them. Let's hope that native support for design-time data comes soon instead.
